import discord
from discord import app_commands
from discord.ui import Button, View, Modal, TextInput
import requests
import json
import base64
import random
import datetime
import traceback

# Import credentials and settings
try:
    import bot_config as config
except ImportError:
    import dev_tools.bot_config as config

# Import XOR crypt functions from encrypt_licenses.py
try:
    from encrypt_licenses import encrypt_database, decrypt_database, SECRET_KEY, xor_encrypt_decrypt
except ImportError:
    from dev_tools.encrypt_licenses import encrypt_database, decrypt_database, SECRET_KEY, xor_encrypt_decrypt

# Intents setup
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

class LicensingBot(discord.Client):
    def __init__(self):
        super().__init__(intents=intents)
        self.tree = app_commands.CommandTree(self)

    async def setup_hook(self):
        # We register the persistent view so the button stays responsive even after bot restarts
        self.add_view(PersistentVerificationView())

client = LicensingBot()

# Helper function to generate a random key matching the bot formatting rules
def generate_key_string(tier: str) -> str:
    if "Lifetime" in tier:
        prefix = "LFT"
    elif "3 Months" in tier or "Quarterly" in tier:
        prefix = "TRM"
    elif "Trial" in tier:
        prefix = "TRL"
    else:
        prefix = "MON" # Default Monthly
        
    hex_chars = "0123456789ABCDEF"
    parts = ["".join(random.choices(hex_chars, k=4)) for _ in range(4)]
    return f"{prefix}-{'-'.join(parts)}"

# Fetch and decrypt the current database payload directly from GitHub Gist
def get_current_db() -> dict:
    url = f"https://api.github.com/gists/{config.GIST_ID}"
    headers = {
        "Authorization": f"Bearer {config.GITHUB_PAT}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Discord-Licensing-Bot"
    }
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        raise Exception(f"Failed to fetch Gist database. HTTP {response.status_code}: {response.text}")
        
    gist_data = response.json()
    db_file_content = gist_data["files"]["db.txt"]["content"].strip()
    
    # Decrypt Gist payload back to dict
    decoded_bytes = base64.b64decode(db_file_content.encode('utf-8'))
    xor_str = decoded_bytes.decode('utf-8')
    json_str = xor_encrypt_decrypt(xor_str, SECRET_KEY)
    return json.loads(json_str)

# Encrypt and upload the updated database payload to GitHub Gist
def save_db_to_gist(db_dict: dict) -> bool:
    # Encrypt the dict
    json_str = json.dumps(db_dict)
    xor_str = xor_encrypt_decrypt(json_str, SECRET_KEY)
    encoded_bytes = base64.b64encode(xor_str.encode('utf-8'))
    encrypted_payload = encoded_bytes.decode('utf-8')
    
    url = f"https://api.github.com/gists/{config.GIST_ID}"
    headers = {
        "Authorization": f"Bearer {config.GITHUB_PAT}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Discord-Licensing-Bot",
        "Content-Type": "application/json"
    }
    payload = {
        "files": {
            "db.txt": {
                "content": encrypted_payload
            }
        }
    }
    response = requests.patch(url, headers=headers, json=payload)
    return response.status_code == 200

# Verify Web Shop Custom Order Details
def verify_web_order(order_id: str) -> dict:
    # Whop integration is disabled as per user preference. 
    # Since payments are processed directly to user card, orders generated by your payment page
    # will be validated directly. For now, to allow custom credit card purchases to activate,
    # we accept standard activation commands or simulate verification of transaction IDs.
    order_id = order_id.strip()
    if order_id.upper().startswith("TXN-") or len(order_id) >= 8:
        upper_id = order_id.upper()
        if "TRL" in upper_id or "TRIAL" in upper_id:
            product = "Trial Subscription"
        elif "MON" in upper_id:
            product = "Monthly Subscription"
        else:
            product = "Lifetime Subscription"
        return {
            "success": True,
            "product_title": product
        }
    return {"success": False, "message": "Invalid Transaction ID / Order ID (رقم طلب غير صحيح)"}

class LicenseActivationModal(Modal, title="Activate Stealth License | تفعيل الاشتراك"):
    order_id = TextInput(
        label="Transaction ID / Order ID (رقم المعاملة)",
        placeholder="Enter the transaction/order ID generated by the payment page (e.g. TXN-XXXX)",
        min_length=6,
        max_length=50,
        required=True
    )
    
    device_id = TextInput(
        label="Device ID / Machine ID (رمز جهازك)",
        placeholder="Paste your PC Machine ID or iOS Device ID (starts with MOB-)",
        min_length=8,
        max_length=60,
        required=True
    )

    async def on_submit(self, interaction: discord.Interaction):
        # Acknowledge immediately to prevent timeout
        await interaction.response.defer(ephemeral=True)
        
        ord_id = self.order_id.value.strip()
        dev_id = self.device_id.value.strip()
        
        # 1. Verify custom order details
        order_res = verify_web_order(ord_id)
        if not order_res["success"]:
            await interaction.followup.send(
                f"❌ **Activation Failed | فشل التفعيل**\n{order_res['message']}\n"
                f"Please ensure you entered the correct Transaction ID from your payment confirmation.", 
                ephemeral=True
            )
            return

        product_title = order_res["product_title"]
        
        # Determine duration & tier
        tier = "Monthly"
        duration_days = 30
        title_lower = product_title.lower()
        
        if "lifetime" in title_lower or "مدى الحياة" in title_lower:
            tier = "Lifetime"
            duration_days = 36500
        elif "3 month" in title_lower or "quarterly" in title_lower or "٣ أشهر" in title_lower:
            tier = "3 Months"
            duration_days = 90
        elif "trial" in title_lower or "تجربة" in title_lower:
            tier = "Trial"
            duration_days = 1
            
        expiry_date = (datetime.date.today() + datetime.timedelta(days=duration_days)).strftime("%Y-%m-%d")
        if tier == "Lifetime":
            expiry_date = "2099-12-31"

        # 2. Get Gist DB and verify duplicate activations
        try:
            db = get_current_db()
            
            # Initialize fields if missing
            if "used_memberships" not in db:
                db["used_memberships"] = []
            if "keys" not in db:
                db["keys"] = {}
                
            if ord_id in db["used_memberships"]:
                await interaction.followup.send(
                    f"❌ **Already Activated | تم التفعيل مسبقاً**\n"
                    f"This Transaction ID `{ord_id}` has already been used to generate a license key.", 
                    ephemeral=True
                )
                return

            # Determine lock types (PC vs Mobile)
            hwid = ""
            mobile_hwid = ""
            if dev_id.upper().startswith("MOB-"):
                mobile_hwid = dev_id
            else:
                hwid = dev_id

            # 3. Generate key and save to dict
            new_key = generate_key_string(tier)
            db["keys"][new_key] = {
                "tier": tier,
                "expiry": expiry_date,
                "hwid": hwid,
                "mobile_hwid": mobile_hwid
            }
            db["used_memberships"].append(ord_id)

            # 4. Upload updated DB back to GitHub Gist
            if not save_db_to_gist(db):
                raise Exception("Gist PATCH request failed.")

            # 5. Automatically grant VIP Customer role to user
            guild = interaction.guild
            member = guild.get_member(interaction.user.id)
            role = guild.get_role(config.VIP_ROLE_ID)
            
            role_added_msg = ""
            if role and member:
                try:
                    await member.add_roles(role)
                    role_added_msg = f"\n✅ You have been granted the **{role.name}** role and VIP channel access!"
                except Exception as role_err:
                    print(f"Failed to assign role: {role_err}")
                    role_added_msg = f"\n⚠️ Verification succeeded, but I couldn't assign the Discord role. Please contact the Admin."

            # 6. Send success response with instructions
            await interaction.followup.send(
                f"🎉 **Stealth Chess Bot Activated Successfully! | تم تفعيل البوت بنجاح!**\n\n"
                f"🔑 **Your Key:** `{new_key}`\n"
                f"📅 **Expiry Date:** `{expiry_date}`\n"
                f"👤 **Device Lock:** `{dev_id}`\n\n"
                f"Please copy your key and paste it inside the Windows EXE or iOS App to play!{role_added_msg}", 
                ephemeral=True
            )

        except Exception as e:
            traceback.print_exc()
            await interaction.followup.send(
                f"❌ **System Error | خطأ في النظام**\n"
                f"An error occurred while updating the license database. Please open a ticket. Error: {str(e)}", 
                ephemeral=True
            )

class PersistentVerificationView(View):
    def __init__(self):
        super().__init__(timeout=None) # Timeout=None makes the button permanent

    @discord.ui.button(
        label="Activate License | تفعيل الترخيص 🔑", 
        style=discord.ButtonStyle.success, 
        custom_id="btn_activate_stealth_chess"
    )
    async def activate_button(self, interaction: discord.Interaction, button: Button):
        # Open the modal popup for the user
        await interaction.response.send_modal(LicenseActivationModal())

@client.event
async def on_ready():
    print("="*60)
    print(f"Bot connected successfully as {client.user}!")
    print("="*60)
    
    # Sync slash commands with guild if configured
    try:
        guild = discord.Object(id=config.DISCORD_GUILD_ID)
        client.tree.copy_global_to(guild=guild)
        await client.tree.sync(guild=guild)
        print("[+] Application slash commands synced successfully.")
    except Exception as e:
        print(f"[-] Command syncing failed: {e}")

@client.tree.command(name="setup_verif_button", description="Sends the persistent license verification button to the configured channel.")
async def setup_verif_button(interaction: discord.Interaction):
    # Ensure only administrators can run this setup command
    if not interaction.user.guild_permissions.administrator:
        await interaction.response.send_message("❌ Admin permissions required.", ephemeral=True)
        return
        
    channel_id = config.VERIFICATION_CHANNEL_ID
    channel = interaction.guild.get_channel(channel_id)
    
    if not channel:
        await interaction.response.send_message(f"❌ Invalid verification channel ID. Please update bot_config.py.", ephemeral=True)
        return
        
    embed = discord.Embed(
        title="♟️ Stealth Chess Assistant - Verification Hub ♟️",
        description=(
            "**Welcome to the self-service activation panel!**\n\n"
            "If you bought a subscription via our Official Website, you can generate and lock your key automatically.\n\n"
            "**1.** Click the button below.\n"
            "**2.** Paste your **Transaction ID / Order ID** (from your payment confirmation screen).\n"
            "**3.** Paste your **Device ID** from the PC EXE or iOS App.\n"
            "**4.** The bot will verify your purchase, issue a locked key, and grant you access to the VIP rooms!\n\n"
            "--- \n\n"
            "**مرحباً بك في مركز التفعيل التلقائي!**\n\n"
            "إذا قمت بشراء اشتراك عبر متجرنا الرسمي، يمكنك توليد وقفل مفتاحك تلقائياً:\n\n"
            "**1.** اضغط على الزر الأخضر بالأسفل.\n"
            "**2.** الصق **رقم المعاملة (Transaction ID)** الذي يظهر لك بعد الدفع.\n"
            "**3.** الصق **رمز جهازك (Device ID / Machine ID)** من برنامج الكمبيوتر أو هاتف الآيفون.\n"
            "**4.** سيتحقق البوت، ويسلمك مفتاحك المقفل، ويفتح لك غرف الـ VIP للتحميل والشرح!"
        ),
        color=0xffa500
    )
    embed.set_thumbnail(url=client.user.avatar.url if client.user.avatar else None)
    embed.set_footer(text="Stealth Chess Bot • Secure Instant Delivery")
    
    await channel.send(embed=embed, view=PersistentVerificationView())
    await interaction.response.send_message(f"✅ Success! Sent verification widget to {channel.mention}.", ephemeral=True)

if __name__ == "__main__":
    if config.DISCORD_BOT_TOKEN == "YOUR_DISCORD_BOT_TOKEN":
        print("[-] ERROR: Please configure your tokens in dev_tools/bot_config.py before launching the bot!")
    else:
        client.run(config.DISCORD_BOT_TOKEN)
